#覆盖访问路径
server:
  servlet:
    context-path: /merchant

#启用Swagger
swagger:
  enable: true

# 配置短信服务参数
sms:
  url: "http://localhost:56085/sailing"
  effectiveTime: 600

# 配置文件上传下载的参数
oss:
  qiniu:
    url: ""
    accessKey: ""
    secretKey: ""
    bucket: ""

# 设置上传文件的最大限制
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 35MB

shanjupay:
  c2b:
    subject: "%s商品"
    body: "向%s付款"