# freemarker的基本配置
spring:
  freemarker:
    charset: UTF-8
    request-context-attribute: rc
    content-type: text/html
    suffix: .html
    enabled: true
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true